apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: middleware
spec:
  type: LoadBalancer
  ports:
    - port: 5672
      name: rabbitmq
    - port: 15672
      name: rabbitmq-management
  selector:
    app: rabbitmq