apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: database
type: Opaque
data:
  root_password: UnVuU2l4XzE5OTRNeVNRTA==
  admin_username: YWRtaW4=
  admin_password: UnVuU2l4XzE5OTRNeVNRTA==