apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: redis