apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
  labels:
    app: cms
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms
  template:
    metadata:
      labels:
        app: cms
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: tier
                    operator: In
                    values:
                      - frontend
      containers:
        - name: cms
          image: runsix1994/cms:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cms
spec:
  ports:
    - port: 80
  selector:
    app: cms
