apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-svc-leaf-v1
  labels:
    app: rs-svc-leaf
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rs-svc-leaf
      version: v1
  template:
    metadata:
      labels:
        app: rs-svc-leaf
        version: v1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: tier
                    operator: In
                    values:
                      - backend
      containers:
        - name: rs-svc-leaf
          image: runsix1994/leaf-server:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rs-svc-leaf
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: rs-svc-leaf
