apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-svc-blog-v1
  labels:
    app: rs-svc-blog
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rs-svc-blog
      version: v1
  template:
    metadata:
      labels:
        app: rs-svc-blog
        version: v1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: tier
                    operator: In
                    values:
                      - backend
      containers:
        - name: rs-svc-blog
          image: runsix1994/rs-svc-blog:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rs-svc-blog
spec:
  ports:
    - name: http-rs-svc-blog
      port: 80
      targetPort: 8080
  selector:
    app: rs-svc-blog
