apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-svc-authserver
  labels:
    app: rs-svc-authserver
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rs-svc-authserver
  template:
    metadata:
      labels:
        app: rs-svc-authserver
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: tier
                    operator: In
                    values:
                      - backend
      containers:
        - name: rs-svc-authserver
          image: runsix1994/rs-svc-authserver:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rs-svc-authserver
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: rs-svc-authserver
